call svn add Release\ConEmu\cecho.cmd
call svn add Release\ConEmu\GitShowBranch.cmd
call svn add Release\ConEmu\Addons\git.cmd
call svn add src\CE.sln
call svn add src\CE10.sln
call svn add src\CE11.sln
call svn add src\CE12.sln
call svn add src\KeyEvents.SysLog
call svn add src\ConEmuLn\ConEmuLn10.vcxproj.filters
call svn add src\ConEmuLn\ConEmuLn11.vcxproj.filters
call svn add src\ConEmuLn\ConEmuLn12.vcxproj.filters
call svn add src\ConEmuLn\ConEmuLn12.vcxproj
call svn add src\ConEmuDW\ConEmuDw10.vcxproj.filters
call svn add src\ConEmuDW\ConEmuDw11.vcxproj.filters
call svn add src\ConEmuDW\ConEmuDw12.vcxproj.filters
call svn add src\ConEmuDW\ConEmuDw12.vcxproj
call svn add src\ConEmuTh\ConEmuTh12.vcxproj
call svn add src\ConEmuTh\ConEmuTh10.vcxproj.filters
call svn add src\ConEmuTh\ConEmuTh11.vcxproj.filters
call svn add src\ConEmuTh\ConEmuTh12.vcxproj.filters
call svn add src\ConEmuTh\Modules\gdip\gdip12.vcxproj
call svn add src\ConEmuTh\Modules\gdip\gdip10.vcxproj.filters
call svn add src\ConEmuTh\Modules\gdip\gdip11.vcxproj.filters
call svn add src\ConEmuTh\Modules\gdip\gdip12.vcxproj.filters
call svn add src\ConEmuTh\Modules\pe\makefile_gcc
call svn add src\ConEmuTh\Modules\pe\pe12.vcxproj
call svn add src\ConEmuTh\Modules\pe\pe10.vcxproj.filters
call svn add src\ConEmuTh\Modules\pe\pe11.vcxproj.filters
call svn add src\ConEmuTh\Modules\pe\pe12.vcxproj.filters
call svn add src\ConEmuTh\Modules\pe\export.gcc.def
call svn add src\ConEmuTh\Modules\pe\makefile_verc0
call svn add src\ConEmuTh\Modules\ico\ico12.vcxproj
call svn add src\ConEmuTh\Modules\ico\ico10.vcxproj.filters
call svn add src\ConEmuTh\Modules\ico\ico11.vcxproj.filters
call svn add src\ConEmuTh\Modules\ico\ico12.vcxproj.filters
call svn add src\ConEmu\version_macro.h
call svn add src\ConEmu\ConEmu12.vcxproj
call svn add src\ConEmu\gen_version.cmd
call svn add src\ConEmu\ConEmu10.vcxproj.filters
call svn add src\ConEmu\ConEmu11.vcxproj.filters
call svn add src\ConEmu\ConEmu12.vcxproj.filters
call svn add src\ConEmu\ConEmu.cbp
call svn add src\ConEmuC\ConEmuC12.vcxproj
call svn add src\ConEmuC\ConEmuC10.vcxproj.filters
call svn add src\ConEmuC\ConEmuC11.vcxproj.filters
call svn add src\ConEmuC\ConEmuC12.vcxproj.filters
call svn add src\ConEmuCD\ConEmuCD12.vcxproj
call svn add src\ConEmuCD\ConEmuCD10.vcxproj.filters
call svn add src\ConEmuCD\ConEmuCD11.vcxproj.filters
call svn add src\ConEmuCD\ConEmuCD12.vcxproj.filters
call svn add src\ConEmuBg\ConEmuBg12.vcxproj
call svn add src\ConEmuBg\ConEmuBg10.vcxproj.filters
call svn add src\ConEmuBg\ConEmuBg11.vcxproj.filters
call svn add src\ConEmuBg\ConEmuBg12.vcxproj.filters
call svn add src\Setup\Logo.png
call svn add src\Setup\ConEmuLogo.png
call svn add src\Setup\CustomAct
call svn add src\Setup\Setupper\libCRT.lib
call svn add src\Setup\Setupper\makefile_vc9
call svn add src\Setup\Setupper\Setupper.sln
call svn add src\Setup\Setupper\makefile_vc
call svn add src\Setup\Setupper\Setupper.vcproj
call svn add src\ConEmuPlugin\ConEmuPlugin12.vcxproj
call svn add src\ConEmuPlugin\ConEmuPlugin10.vcxproj.filters
call svn add src\ConEmuPlugin\ConEmuPlugin11.vcxproj.filters
call svn add src\ConEmuPlugin\ConEmuPlugin12.vcxproj.filters
call svn add src\ConEmuHk\ConEmuHk12.vcxproj
call svn add src\ConEmuHk\ConEmuHk10.vcxproj.filters
call svn add src\ConEmuHk\ConEmuHk11.vcxproj.filters
call svn add src\ConEmuHk\ConEmuHk12.vcxproj.filters
